### ISSUE TITLE
License

### ISSUE THREAD

**Issue by renanborgez** [ugglr/react-native-value-picker#6]
Hi,

I really liked of playing and using this component, however without a license I'm not allowed to install it in the projects of the company that I work at.

Could you please add a formal license file for this project? I know there is a field on the package.json informing that is under MIT, but a license file would make it more explicit :)

thanks

**Comment by ugglr** [comment]
Hi @renanborgez ! Thank you so much for telling me that you enjoy using my package! I have added a MIT license file, hope that enables you to use it even more  🚀🎉
